name: partygames
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.0
  page_transition: ^2.0.9
  web_socket_channel: ^2.4.0
<<<<<<< HEAD
  html: ^0.15.4
  http: ^1.1.0
  timer_count_down: ^2.2.2
=======
  http: ^1.1.0
>>>>>>> refs/remotes/origin/main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
  - family: Beon
    fonts:
      - asset: ./assets/Beon-Regular.ttf
  - family: Adlamd
    fonts:
      - asset: ./assets/ADLaMDisplay-Regular.ttf
  assets:
    - assets/Werewolf/Dorfbewohner.webp
    - assets/Werewolf/1.png


